### PR TITLE
ROS 2 port

### PR DESCRIPTION
**Pull request by vmayoral**
*DO NOT MERGE*

Following @clalancette guidelines, we're requesting a `ros2` branch.
Will re-submit the PR once it's been created.

### CODE REVIEW

**Comment by rhaschke** [comment]
I created a ros2 branch and directed this PR onto this new branch.

**Comment by rhaschke** [comment]
Is there already a ROS2-directed CI framework for Travis?

**Comment by vmayoral** [comment]
@rhaschke certain ROS 2 packages have enabled CI through Jenkins. E.g. see  https://github.com/ros2/geometry2/pull/90. Not sure what's required to get random_numbers there though. Requesting input from @tfoote and @clalancette.

**Comment by tfoote** [comment]
@vmayoral The PR builds are enabled in the rosdistro just like ROS1: https://github.com/ros/rosdistro/blob/c6b6354dcc754d7e759afe888302676c986123c0/crystal/distribution.yaml#L562

**Comment by jdlangs** [comment]
@rhaschke @vmayoral can this be merged now?

**Comment by rhaschke** [comment]
Sorry, I cannot help on ROS2 reviews.

**Comment by mlautman** [comment]
Let's get travis working on this branch. I will be able to spend some more time on this tomorrow

**Comment by rhaschke** [comment]
Superseeded by #14.

**Pull request closed without merging**
